### ISSUE TITLE
Question on the project

### ISSUE THREAD

**Issue by franciszchen** [blackccpie/fastconv#1]
What's the difference between the function 'convolve' and 'fast_convolve'? And where to use the function 'multiply'?
I thought the project is to show the efficiency of three convolution implementation 'convolve',  'fast_convolve' and im2col matrix 'multiply'. 
Thank you!

**Comment by blackccpie** [comment]
@HonestmanChen : I implemented the multiply functions for the `static_matrix` and `dynamic_matrix` classes, but they are not used and not benchmarked in the project, so you're right I could have removed them for the sake of simplicity and clarity.
Concerning convolutions, `convolve` is the standard kernel convolution naive implementation, whereas `fast_convolve` is the im2col-inspired implementation, with additional _simd_ optimisations.

Hope this helps,

Regards
